name: Bug Report
description: Report an issue or bug
title: '[BUG]: <issue title>'
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Please provide a clear and concise description of what the bug is.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: A brief summary of the issue
      placeholder: Enter a brief summary of the issue
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the bug
      placeholder: Enter the steps to reproduce the bug
      value: |
        1. Step one
        2. Step two
        3. Step three
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: Enter what you expected to happen
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: Enter what actually happened
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the issue
      placeholder: Add screenshots here
