name: Lint and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          cache: true

      - name: Cache Gradle dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze --fatal-infos --no-pub

      - name: Run tests
        run: flutter test --no-pub

      - name: Build Debug APK
        run: flutter build apk --debug --no-pub

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v7
        with:
          path: build/app/outputs/flutter-apk/app-debug.apk
          archive: false
